import { useState } from "react";
import { useRouter } from "next/navigation";
import { UseFormReturn } from "react-hook-form";
import { useAuth } from "@/src/components/AuthProvider";
import { insertUserProfile, uploadResume } from "@/src/lib/profileFunctions";
import type { ProfileFormValues } from "@/src/app/profile/schema";

interface UseProfileSubmissionReturn {
  isSubmitting: boolean;
  noticeOpen: boolean;
  noticeTitle: string;
  noticeDescription: string;
  noticeVariant: "success" | "error" | "info";
  handleSubmit: () => Promise<void>;
  closeNotice: () => void;
}

export function useProfileSubmission(
  methods: UseFormReturn<ProfileFormValues>
): UseProfileSubmissionReturn {
  const router = useRouter();
  const { user, refreshProfile } = useAuth();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [noticeOpen, setNoticeOpen] = useState(false);
  const [noticeTitle, setNoticeTitle] = useState("");
  const [noticeDescription, setNoticeDescription] = useState("");
  const [noticeVariant, setNoticeVariant] = useState<"success" | "error" | "info">("info");

  const handleSubmit = async () => {
    console.log("[Profile] handleSubmit called");

    if (!user) {
      console.error("[Profile] No user found");
      setNoticeTitle("Authentication Required");
      setNoticeDescription(
        "You must be logged in to save your profile. Please sign in and try again."
      );
      setNoticeVariant("error");
      setNoticeOpen(true);
      setTimeout(() => {
        router.push("/auth/sign-in");
      }, 2000);
      return;
    }

    console.log("[Profile] User authenticated, starting save process");
    setIsSubmitting(true);

    // Show loading modal
    setNoticeTitle("Creating Your Profile");
    setNoticeDescription("Please wait while we save your profile information...");
    setNoticeVariant("info");
    setNoticeOpen(true);

    try {
      const data = methods.getValues();
      console.log("[Profile] Form data:", {
        fullname: data.fullname,
        email: data.email,
        primary_trade: data.primary_trade,
        hasResumeFile: !!(data as any).resumeFile,
      });

      // Handle resume file upload if present
      let resumeUrl = data.resume_file_url;
      const resumeFile = (data as any).resumeFile as File | undefined;

      if (resumeFile) {
        console.log("[Profile] Uploading resume file:", resumeFile.name);
        setNoticeDescription("Uploading your resume...");
        try {
          resumeUrl = await uploadResume(resumeFile, user.id);
          console.log("[Profile] Resume uploaded, URL:", resumeUrl);
          setNoticeDescription("Resume uploaded! Saving your profile...");
        } catch (uploadError: any) {
          console.error("[Profile] Resume upload failed:", uploadError.message);
          throw new Error(`Failed to upload resume: ${uploadError.message}`);
        }
      }

      const profileData = {
        id: user.id,
        fullname: data.fullname,
        email: data.email,
        phone_number: data.phone_number,
        city: data.city,
        state: data.state,
        primary_trade: data.primary_trade,
        years_of_experience: data.years_of_experience,
        shift_preference: data.shift_preference,
        has_valid_licence: data.has_valid_licence || false,
        resume_file_url: resumeUrl,
        created_by: user.id,
        role: data.role || "candidate",
        priority: data.priority || 1,
        company_id: data.company_id || null,
        priority_choice: data.priority_choice,
        shape_choice: data.shape_choice,
        // timestamp will be auto-generated by database
      };

      console.log("[Profile] Calling insertUserProfile...");
      await insertUserProfile(profileData);
      console.log("[Profile] Profile inserted successfully");

      console.log("[Profile] Refreshing profile in AuthProvider...");
      await refreshProfile();
      console.log("[Profile] Profile refreshed");

      // Show success modal
      setNoticeTitle("Profile Created Successfully!");
      setNoticeDescription(
        "Your profile has been created. You'll be redirected to view your profile."
      );
      setNoticeVariant("success");
      setNoticeOpen(true);

      // Redirect after showing success message
      setTimeout(() => {
        router.push("/candidate/profile/view");
      }, 2000);
    } catch (error: any) {
      console.error("[Profile] Save error:", error);
      console.error("[Profile] Error message:", error.message);
      console.error("[Profile] Error stack:", error.stack);

      // Show error modal
      setNoticeTitle("Failed to Create Profile");
      setNoticeDescription(
        error.message ||
          "An error occurred while saving your profile. Please try again."
      );
      setNoticeVariant("error");
      setNoticeOpen(true);
    } finally {
      console.log("[Profile] Setting isSubmitting to false");
      setIsSubmitting(false);
    }
  };

  const closeNotice = () => {
    setNoticeOpen(false);
    if (noticeVariant === "error" && noticeTitle === "Authentication Required") {
      router.push("/auth/sign-in");
    }
  };

  return {
    isSubmitting,
    noticeOpen,
    noticeTitle,
    noticeDescription,
    noticeVariant,
    handleSubmit,
    closeNotice,
  };
}

